language: go
sudo: false
go:
  - 1.9.x
go_import_path: telegraph
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
  - git config --global http.https://gopkg.in.followRedirects true
  - glide install
script:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go test -v -cover -coverprofile=line.coverage.out -covermode=set
  - cat *.coverage.out >> coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN